import Head from 'next/head'
import Image from 'next/image'
import { ConnectButton } from '@rainbow-me/rainbowkit'
import Tool from '../components/list-item'

const tools = [
  {
    name: 'Ethereum',
    path: './eth',
    color: 'linear-gradient(92.29deg, #89AAF3 0%, #C7B1F6 100%)',
  },
  {
    name: 'Ethereum Name Service',
    path: './ens',
    color: 'linear-gradient(92.29deg, #879AF4 0%, #66B9EB 100%)',
  },
  {
    name: '1inch Network',
    path: './1inch',
    color: 'linear-gradient(92.29deg, #20438C 0%, #280F31 100%)',
  },
  {
    name: 'Lens Protocol',
    path: './lens',
    color: '#005017',
  },
  {
    name: 'Optimism',
    path: './optimism',
    color: '#EA3431',
  },
  {
    name: 'Gambling',
    path: './gambling',
    color: '#19191A',
  },
  {
    name: 'Polygon',
    path: './polygon',
    color: '#7257D5',
  },
]

export default function Home() {
	return (
		<div className="container">
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

      <header className="header">
        <h1 className="title">Simplify Your Ethereum Toolkit</h1>
        <span className="subtitle">Replace dozens of bookmarked websites with one that does it all.</span>
      </header>

      <div className="tools">
        {tools.map((tool, i) => (
          <Tool key={i} name={tool.name} path={tool.path} color={tool.color} />
        ))}
      </div>

			<main>
				<ConnectButton />
			</main>
		</div>
	)
}
